spring:
  application:
    name: adaptor-app
info.app.name: @project.artifactId@
info.app.version: @project.version@

#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
#spring.datasource.url: jdbc:mysql://localhost:3306/intact-ats-database
#spring.datasource.username: root
#spring.datasource.password: root

server:
  port: 8080
