spring:
  application:
    name: myrule-api
info.app.name: @project.artifactId@
info.app.version: @project.version@

application.title:  @project.artifactId@
application.version: @project.version@
server:
  port: 8080
