spring.datasource.driver-class-name: org.h2.Driver
#spring.datasource.url: jdbc:h2:mem:adaptor-database
spring.datasource.url: jdbc:h2:file:D:\toBeRenoved\adaptor-database\database\adaptor.db
spring.datasource.username:
spring.datasource.password:
